apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: 043509840788.dkr.ecr.eu-west-2.amazonaws.com/my-eks-cluster-hello-world
        imagePullPolicy: Always
        ports:
        - containerPort: 5000